/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppNotification {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : bigint,
}
export interface CivilService {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
}
export interface GalleryPhoto {
  'id' : bigint,
  'sub' : string,
  'url' : string,
  'timestamp' : bigint,
  'caption' : string,
}
export interface GrievanceSubmission {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'mobile' : string,
}
export interface Project {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface ProjectRating {
  'id' : bigint,
  'name' : string,
  'comment' : string,
  'projectId' : bigint,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface Scheme {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'description' : string,
  'eligibility' : string,
  'category' : string,
  'benefit' : string,
}
export interface TeamMember {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'description' : string,
  'photoUrl' : string,
  'mobile' : string,
}
export interface _SERVICE {
  'addCivilService' : ActorMethod<[string, string, string, string], bigint>,
  'addGalleryPhoto' : ActorMethod<[string, string, string], bigint>,
  'addNotification' : ActorMethod<[string, string], bigint>,
  'addProject' : ActorMethod<[string, string, string, string], bigint>,
  'addScheme' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addTeamMember' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deleteCivilService' : ActorMethod<[bigint], boolean>,
  'deleteGalleryPhoto' : ActorMethod<[bigint], boolean>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'deleteScheme' : ActorMethod<[bigint], boolean>,
  'deleteTeamMember' : ActorMethod<[bigint], boolean>,
  'getAllCivilServices' : ActorMethod<[], Array<CivilService>>,
  'getAllGalleryPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'getAllGrievances' : ActorMethod<[], Array<GrievanceSubmission>>,
  'getAllNotifications' : ActorMethod<[], Array<AppNotification>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllRatings' : ActorMethod<[], Array<ProjectRating>>,
  'getAllSchemes' : ActorMethod<[], Array<Scheme>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAverageRating' : ActorMethod<
    [bigint],
    { 'totalRatings' : bigint, 'averageRating' : bigint }
  >,
  'getRatingsForProject' : ActorMethod<[bigint], Array<ProjectRating>>,
  'getSitePhoto' : ActorMethod<[string], string>,
  'getUnreadGrievanceCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'markAllNotificationsRead' : ActorMethod<[], boolean>,
  'markGrievancesRead' : ActorMethod<[], boolean>,
  'setSitePhoto' : ActorMethod<[string, string], boolean>,
  'submitGrievance' : ActorMethod<[string, string, string], bigint>,
  'submitRating' : ActorMethod<[bigint, bigint, string, string], bigint>,
  'toggleCivilService' : ActorMethod<[bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];