/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GalleryPhoto {
    id: bigint;
    sub: string;
    url: string;
    timestamp: bigint;
    caption: string;
}
export interface ProjectRating {
    id: bigint;
    name: string;
    comment: string;
    projectId: bigint;
    timestamp: bigint;
    rating: bigint;
}
export interface Scheme {
    id: bigint;
    status: string;
    title: string;
    description: string;
    eligibility: string;
    category: string;
    benefit: string;
}
export interface Project {
    id: bigint;
    status: string;
    title: string;
    description: string;
    category: string;
}
export interface GrievanceSubmission {
    id: bigint;
    name: string;
    message: string;
    timestamp: bigint;
    mobile: string;
}
export interface backendInterface {
    addGalleryPhoto(url: string, caption: string, sub: string): Promise<bigint>;
    addProject(title: string, description: string, category: string, status: string): Promise<bigint>;
    addScheme(title: string, description: string, category: string, status: string, benefit: string, eligibility: string): Promise<bigint>;
    adminLogin(password: string): Promise<boolean>;
    deleteGalleryPhoto(id: bigint): Promise<boolean>;
    deleteProject(id: bigint): Promise<boolean>;
    deleteScheme(id: bigint): Promise<boolean>;
    getAllGalleryPhotos(): Promise<Array<GalleryPhoto>>;
    getAllGrievances(): Promise<Array<GrievanceSubmission>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllRatings(): Promise<Array<ProjectRating>>;
    getAllSchemes(): Promise<Array<Scheme>>;
    getAverageRating(projectId: bigint): Promise<{
        totalRatings: bigint;
        averageRating: bigint;
    }>;
    getRatingsForProject(projectId: bigint): Promise<Array<ProjectRating>>;
    submitGrievance(name: string, mobile: string, message: string): Promise<bigint>;
    submitRating(projectId: bigint, rating: bigint, name: string, comment: string): Promise<bigint>;
    updateAdminPassword(oldPassword: string, newPassword: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGalleryPhoto(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryPhoto(arg0, arg1, arg2);
            return result;
        }
    }
    async addProject(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addScheme(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addScheme(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScheme(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async adminLogin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async deleteGalleryPhoto(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryPhoto(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteScheme(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheme(arg0);
            return result;
        }
    }
    async getAllGalleryPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryPhotos();
            return result;
        }
    }
    async getAllGrievances(): Promise<Array<GrievanceSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGrievances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGrievances();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAllRatings(): Promise<Array<ProjectRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRatings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRatings();
            return result;
        }
    }
    async getAllSchemes(): Promise<Array<Scheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSchemes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSchemes();
            return result;
        }
    }
    async getAverageRating(arg0: bigint): Promise<{
        totalRatings: bigint;
        averageRating: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return result;
        }
    }
    async getRatingsForProject(arg0: bigint): Promise<Array<ProjectRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsForProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsForProject(arg0);
            return result;
        }
    }
    async submitGrievance(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGrievance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGrievance(arg0, arg1, arg2);
            return result;
        }
    }
    async submitRating(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminPassword(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
